FROM python:3.9

WORKDIR /app

COPY ./backend /app

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN pip install -r requirements -i https://mirrors.aliyun.com/pypi/simple/

RUN chmod +x /app/start.sh

EXPOSE 8101

ENTRYPOINT ["/app/start.sh"]

#docker run --restart=always -d --name triangle_dog -p 8092:8092 triangle
